[package]
name = "pdfmark-gen"
version = "0.1.0"
authors = ["silmeth <sth.jaworski@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
encoding = "0.2"
